/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Runtime options configurable from JavaScript. */
export interface JsRuntimeOptions {
  /** Orchestration concurrency (default: 4) */
  orchestrationConcurrency?: number
  /** Worker/activity concurrency (default: 8) */
  workerConcurrency?: number
  /** Dispatcher poll interval in ms (default: 100) */
  dispatcherPollIntervalMs?: number
}
/** Orchestration status returned to JS. */
export interface JsOrchestrationStatus {
  status: string
  output?: string
  error?: string
}
/** System metrics returned to JS. */
export interface JsSystemMetrics {
  totalInstances: number
  totalExecutions: number
  runningInstances: number
  completedInstances: number
  failedInstances: number
  totalEvents: number
}
/** Queue depths returned to JS. */
export interface JsQueueDepths {
  orchestratorQueue: number
  workerQueue: number
  timerQueue: number
}
/** Instance info returned to JS. */
export interface JsInstanceInfo {
  instanceId: string
  orchestrationName: string
  orchestrationVersion: string
  currentExecutionId: number
  status: string
  output?: string
  createdAt: number
  updatedAt: number
  parentInstanceId?: string
}
/** Execution info returned to JS. */
export interface JsExecutionInfo {
  executionId: number
  status: string
  output?: string
  startedAt: number
  completedAt?: number
  eventCount: number
}
/** Instance tree returned to JS. */
export interface JsInstanceTree {
  rootId: string
  allIds: Array<string>
  size: number
}
/** Delete result returned to JS. */
export interface JsDeleteInstanceResult {
  instancesDeleted: number
  executionsDeleted: number
  eventsDeleted: number
  queueMessagesDeleted: number
}
/** Prune options from JS. */
export interface JsPruneOptions {
  keepLast?: number
  completedBefore?: number
}
/** Prune result returned to JS. */
export interface JsPruneResult {
  instancesProcessed: number
  executionsDeleted: number
  eventsDeleted: number
}
/** Instance filter from JS. */
export interface JsInstanceFilter {
  instanceIds?: Array<string>
  completedBefore?: number
  limit?: number
}
/** A single history event returned to JS. */
export interface JsEvent {
  eventId: number
  kind: string
  sourceEventId?: number
  timestampMs: number
}
/**
 * Emit an activity trace through the current Rust ActivityContext.
 * Delegates to ActivityContext.trace_info/warn/error/debug which includes
 * all structured fields (instance_id, activity_name, activity_id, worker_id, etc.)
 */
export declare function activityTraceLog(token: string, level: string, message: string): void
/**
 * Emit an orchestration trace through the Rust OrchestrationContext.
 * Delegates to OrchestrationContext.trace() which checks is_replaying
 * and includes all structured fields (instance_id, orchestration_name, etc.)
 */
export declare function orchestrationTraceLog(instanceId: string, level: string, message: string): void
/** Wraps duroxide's Client for use from JavaScript. */
export declare class JsClient {
  constructor(provider: JsSqliteProvider)
  /** Create a client backed by PostgreSQL. */
  static fromPostgres(provider: JsPostgresProvider): JsClient
  /** Start a new orchestration instance. */
  startOrchestration(instanceId: string, orchestrationName: string, input: string): Promise<void>
  /** Start a new orchestration instance with a specific version. */
  startOrchestrationVersioned(instanceId: string, orchestrationName: string, input: string, version: string): Promise<void>
  /** Get the current status of an orchestration instance. */
  getStatus(instanceId: string): Promise<JsOrchestrationStatus>
  /** Wait for an orchestration to complete (with timeout in milliseconds). */
  waitForOrchestration(instanceId: string, timeoutMs: number): Promise<JsOrchestrationStatus>
  /** Cancel a running orchestration instance. */
  cancelInstance(instanceId: string, reason?: string | undefined | null): Promise<void>
  /** Raise an external event to an orchestration instance. */
  raiseEvent(instanceId: string, eventName: string, data: string): Promise<void>
  /** Get system metrics (if provider supports management). */
  getSystemMetrics(): Promise<JsSystemMetrics>
  /** Get queue depths (if provider supports management). */
  getQueueDepths(): Promise<JsQueueDepths>
  /** List all orchestration instance IDs. */
  listAllInstances(): Promise<Array<string>>
  /** List orchestration instance IDs by status. */
  listInstancesByStatus(status: string): Promise<Array<string>>
  /** Get detailed info about a specific instance. */
  getInstanceInfo(instanceId: string): Promise<JsInstanceInfo>
  /** Get detailed info about a specific execution within an instance. */
  getExecutionInfo(instanceId: string, executionId: number): Promise<JsExecutionInfo>
  /** List execution IDs for an instance. */
  listExecutions(instanceId: string): Promise<Array<number>>
  /** Read the event history for a specific execution. */
  readExecutionHistory(instanceId: string, executionId: number): Promise<Array<JsEvent>>
  /** Get the full instance tree (root + all descendants). */
  getInstanceTree(instanceId: string): Promise<JsInstanceTree>
  /** Delete an orchestration instance and all its data. */
  deleteInstance(instanceId: string, force: boolean): Promise<JsDeleteInstanceResult>
  /** Delete multiple instances matching a filter. */
  deleteInstanceBulk(filter: JsInstanceFilter): Promise<JsDeleteInstanceResult>
  /** Prune old executions from a single instance. */
  pruneExecutions(instanceId: string, options: JsPruneOptions): Promise<JsPruneResult>
  /** Prune old executions from multiple instances matching a filter. */
  pruneExecutionsBulk(filter: JsInstanceFilter, options: JsPruneOptions): Promise<JsPruneResult>
}
/** Wraps duroxide-pg's PostgresProvider for use from JavaScript. */
export declare class JsPostgresProvider {
  /**
   * Connect to a PostgreSQL database.
   * Uses the default "public" schema.
   */
  static connect(databaseUrl: string): Promise<JsPostgresProvider>
  /**
   * Connect to a PostgreSQL database with a custom schema.
   * The schema will be created if it does not exist.
   */
  static connectWithSchema(databaseUrl: string, schema: string): Promise<JsPostgresProvider>
}
/** Wraps duroxide's SqliteProvider for use from JavaScript. */
export declare class JsSqliteProvider {
  /**
   * Open a SQLite database at the given file path.
   * Path should be a sqlite: URL, e.g. "sqlite:./data.db" or "sqlite:/tmp/test.db".
   * The file will be created if it does not exist.
   */
  static open(path: string): Promise<JsSqliteProvider>
  /** Create an in-memory SQLite database (useful for testing). */
  static inMemory(): Promise<JsSqliteProvider>
}
/** Builder for the duroxide runtime, wrapping registration and startup. */
export declare class JsRuntime {
  constructor(provider: JsSqliteProvider, options?: JsRuntimeOptions | undefined | null)
  /** Create a runtime backed by PostgreSQL. */
  static fromPostgres(provider: JsPostgresProvider, options?: JsRuntimeOptions | undefined | null): JsRuntime
  /**
   * Set the generator driver functions (called once from JS before registering orchestrations).
   * These three functions handle: creating generators, driving next steps, and disposing.
   */
  setGeneratorDriver(createFn: (arg: string) => any, nextFn: (arg: string) => any, disposeFn: (arg: string) => any): void
  /**
   * Register a JavaScript activity function.
   * The JS function receives (contextInfoJson, input) and returns a Promise<string>.
   */
  registerActivity(name: string, callback: (arg: string) => any): void
  /**
   * Register a JavaScript orchestration (generator function).
   * The orchestration name is used for both registration and the generator function lookup.
   */
  registerOrchestration(name: string): void
  /** Register a versioned JavaScript orchestration. */
  registerOrchestrationVersioned(name: string, version: string): void
  /**
   * Start the runtime. This processes orchestrations and activities until shutdown.
   *
   * # Safety
   * This is async and takes &mut self. napi-rs requires async &mut methods to be marked unsafe.
   */
  start(): Promise<void>
  /** Shutdown the runtime gracefully. */
  shutdown(timeoutMs?: number | undefined | null): Promise<void>
}
